production:
  LGDHSFOOFY190002:
    mod_number: 1
    start_date: "2018-02-05"
    end_date: "2023-02-04"
    estimated_amount: 2_121_412
    iaa_status: active
    partner_account: DHS-FOO

  LGDODBARFY200002:
    mod_number: 0
    start_date: "2019-05-24"
    end_date: "2024-05-23"
    estimated_amount: 3_141_231
    iaa_status: active
    partner_account: DOD-BAR

  LGGSATTSFY210001:
    mod_number: 0
    start_date: "2021-04-07"
    end_date: "2026-04-06"
    estimated_amount: 1_000_000
    iaa_status: active
    partner_account: GSA-TTS
