production:
  DHS-FOO:
    name: "Federal Office of Operations"
    agency: DHS
    partner_account_status: active
    crm_id: 12345
    became_partner: "2018-02-05"
    contacts:
      - "hello@dhs.gov"

  DOD-BAR:
    name: "Bureau of Awesome Research"
    agency: DOD
    partner_account_status: active
    crm_id: 23456
    became_partner: "2019-05-24"
    contacts:
      - "person@dod.mil"

  GSA-TTS:
    name: "Technology Transformation Services"
    agency: GSA
    partner_account_status: active
    crm_id: 51213
    became_partner: "2021-04-06"
    contacts:
      - "oren.kanner@gsa.gov"
